### ISSUE TITLE
tracked site sometimes displays basic auth popup

### ISSUE THREAD

**Issue by dwrensha** [zarvox/piwik#2]
eglimi on IRC reports that occasionally a basic auth prompt will pop up for an Oasis URL. Maybe there are some code paths for which the request to Piwik does not get the proper credentials?

**Comment by zarvox** [comment]
This is likely a result of the changes to how API hosts are handled -- in particular, it will primarily affect users who have Javascript disabled.

In the past, we would simply not track those users at all, since we did not allow unauthenticated GETs against the API endpoint, and the endpoint would not prompt for authorization.

Now, however, the API endpoint accepts basic auth, and will prompt users for basic auth credentials when the site being tracked falls back to `<img src>`-based tracking.  So Piwik grains created in the last week or so will have this odd behavior when a user has script disabled on a page.

We can fix this in a reasonably straightforward manner by switching to using the Basic Auth URL, and putting the key in the URL that we instruct users to copy.

One upside of the change to allow basic auth is that I think we'll be able to observe GET requests from these users.  We won't be able to geolocate users with script disabled, though, since they won't be sending the `X-Sandstorm-Passthrough: address` header.  But now we'll at least be able to see that they exist (though they may all be collapsed into a single ApiSession, so they might not be distinguishable from each other).

However, this has a second issue, which is that we need to not break existing tracker snippets embedded in webpages on upgrade.  I think the easiest way to deal with this is to keep the old `piwik.js` around forever, and make the new snippets use a new `piwik2.js` which eschews the `Authorization: Bearer <token>` header, but still prefers POSTs and still adds the `X-Sandstorm-Passthrough: address` header when scripts are available.

**Comment by eglimi** [comment]
It was me who reported this issue on IRC. Thank you for the analysis, and please let me know if I can help with more information.

I saw this issue 3 or 4 times in one week. It was just a blank basic auth popup. I use Firefox with Javascript enabled, and some plugins such as uBlock Origin and Ghostery.

I have Piwik currently disabled on my website, because I want to avoid that other users receive the popup. But I'm happy to enable it again, maybe with a `piwik2.js`.

**Comment by zarvox** [comment]
This is more complicated than I originally thought.

Due to a [lack of](https://support.saucelabs.com/customer/portal/articles/2005327-how-can-i-use-http-basic-auth-in-safari-) [browser support](http://stackoverflow.com/questions/23498710/basic-authentication-with-selenium-in-internet-explorer-10) for HTTP basic auth credentials in URLs, and the fact that people using Piwik probably expect it to not cause this sort of annoyance to people using IE, I don't think we can actually do the `<img src>` based tracking reliably and safely.  We could theoretically try to detect when the user is using a browser that _would_ be able to use the pixel tracker without triggering a prompt, but that is likely to be complicated, produces lower-quality tracking info to begin with, and isn't something I really want to spend a lot of effort maintaining.

I think the best approach here is going to be to just disable the `<img src>` fallback in the JS - we've already turned it off for the `<noscript>` case, and you lose no tracking information that you would have (with Sandstorm before the platform allowed general HTTP Basic Auth on API endpoints) successfully received.

**Comment by zarvox** [comment]
This should be fixed by 3338d31fe2ddb3323d26a73f6aa7d5f232cf3475 .

I just uploaded 2.15.0-sandstorm-4 to the app index for review; I imagine it'll be approved in the next 24 hours.
